# Generated by Django 2.0.5 on 2018-05-22 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20180522_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 22, 23, 31, 18, 721095, tzinfo=utc)),
        ),
    ]
